# Generated by Django 2.2.14 on 2020-07-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
